###服务器端口号
server:
  port: 80

####spring_cloud gateway
spring:
  application:
    name: app-bv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: app-bv-member
          uri: lb://app-bv-member
          filters:
            - StripPrefix=1
          predicates:
            - Path=/member/**

        - id: app-bv-wechat
          uri: lb://app-bv-wechat
          filters:
            - StripPrefix=1
          predicates:
            - Path=/wechat/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
  instance:
    prefer-ip-address: true


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


